# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RemoteSwitch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RemoteSwitch
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'

  target 'RemoteSwitch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RemoteSwitchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RemoteSwitch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RemoteSwitch-tvOS

end
